### ISSUE TITLE
"Zeiterfassung" fehlt gänzlich im Handbuch

### ISSUE THREAD

**Issue by J0hhny** [pentacode/site#10]
@MaKleSoft 
Der Reiter Zeiterfassung wurde bis jetzt gar nicht im Handbuch behandelt. 
Als Spiegel der digitalen Stempeluhr sollte der Reiter ja ziemlich selbsterklärend sein, aber ich würd mir nach Dienstplan und digitaler Stempeluhr diesen Punkt mal als nächstes vornehmen
![manage demo pentacode app_time_venue=99 date=2022-07-05 next=time tab=0(iPad Air)](https://user-images.githubusercontent.com/104359585/177316637-7d44a2cc-40c4-4f07-8900-4150c9263f59.png)
.

**Comment by MaKleSoft** [comment]
Doch, da gibt es schon einen Artikel. Ist unter "Digitale Stempeluhr" zu finden: https://pentacode.app/hilfe/handbuch/stempeluhr/tagesuebersicht/

**Comment by MaKleSoft** [comment]
@J0hhny Der müsste aber wahrscheinlich auch mal wieder geupdated werden...

**Comment by J0hhny** [comment]
geklärt
