### ISSUE TITLE
Allow editing pages under /funktionen/ via Netflify

### ISSUE THREAD

**Issue by MaKleSoft** [pentacode/site#41]
Not sure if this is possible with reasonable effort, but it would be great if it were possible to edit (or even create!) pages under `/funktionen/`. I guess what we'd need are two fairly complex widgets, one for the "hero" section at the top and then one for the subsequent sections with the boxes and horizontal image slider (or maybe the hero section can be "static" and the title, subtitle etc, can be provided via the front matter, since it only appears once) . @BrunoBernardino Do you think that's possible?

**Comment by BrunoBernardino** [comment]
@MaKleSoft it's definitely possible, including also other kinds of pages and metadata, etc., but it takes a bit of time to properly setup. I can do it for specific pages or folders, or just `funktionen` for now, which will also need those widgets you mention.

**Comment by MaKleSoft** [comment]
Just `/funktionen` will do for now.
