### ISSUE TITLE
Can't save page in CRM

### ISSUE THREAD

**Issue by MaKleSoft** [pentacode/site#44]
<img width="878" alt="Screenshot 2022-09-20 at 08 54 56" src="https://user-images.githubusercontent.com/1270940/191188069-a5e843b6-4496-4876-bd17-5a71e72c24b4.png">

**Comment by BrunoBernardino** [comment]
Oh, I'll have to confirm this tomorrow, but if this didn't work, we might need to always define a slug (I'll try to default it to the automated slug, but don't know if that will work).
