### ISSUE TITLE
Figure widget isn't being show as widget after saving

### ISSUE THREAD

**Issue by MaKleSoft** [pentacode/site#50]
After saving a draft and reopening, the figure widget is no longer being displayed as a widget but as html. Also, the image is now visible in the preview.

<img width="819" alt="Screenshot 2022-09-22 at 15 18 06" src="https://user-images.githubusercontent.com/1270940/191757699-47ed72de-1d29-4acd-b103-a9fe5ce94f19.png">

**Comment by BrunoBernardino** [comment]
@MaKleSoft I suspect this is a case of the admin regexp limitations. If you add something to the "alt", does that make the widget come back?

**Comment by MaKleSoft** [comment]
Nope, same problem
