### ISSUE TITLE
Im Blog keinen Kategorienfilter für "Aktuelles"

### ISSUE THREAD

**Issue by J0hhny** [pentacode/site#63]
![localhost_9090_blog_(Surface Pro 7)](https://user-images.githubusercontent.com/104359585/201472772-3d6fccce-6495-47e4-84e5-f094f90e9f4b.png)

Mir ist aufgefallen, dass man oben im Blog nicht nach der Kategorie "Aktuelles" Suchen kann. Wäre vielleicht eine ergänzende Funktion.

**Comment by MaKleSoft** [comment]
Hatten wir vorübergehend versteckt weil es noch nicht genügend Artikel unter "Aktuelles" gab. Ist im `master` branch schon wieder hinzugefügt.
