### ISSUE TITLE
Fallbeschreibung für Handbuch zur Urlaubsbuchung bei Neukunden

### ISSUE THREAD

**Issue by Thomasino21** [pentacode/site#8]
@J0hhny 
Folgende Fallbeschreibung wäre für das Handbuch wichtig.
Neukunden müssen in Pentacode Zeit- und Urlaubsbuchungen ihrer Mitarbeiter vornehmen, um Altlasten aus deren vorherigen System in Pentacode zu übernehmen. Hierzu gibt es noch keinen entsprechenden Hilfeartikel.
Wichtig dabei ist, das bei einem Übertrag zu berücksichtigen ist, dass ab Vertragsbeginn Pentacode die weitere Zählung des Urlaubszuwachses übernimmt. Somit muss der verbleibende Jahreszeitraum vom eigentlich mitgebrachten Resturlaubs eines Mitarbeiters abgezogen und dann entsprechend verbucht werden.
Zu diesem Thema habe ich für eine Kundin zwei Beispiele bearbeitet:
<img width="443" alt="image" src="https://user-images.githubusercontent.com/53435626/176892415-08e1de33-7ce8-4640-b5e7-34e082c17751.png">

**Comment by J0hhny** [comment]
@Thomasino21 
Verstehe grundsätzlich den Bedarf einer genaueren Erklärung zum Übertragen von Urlaubsansprüchen. Ich werde leider nur aus deiner Schilderung nicht ganz schlau. Am besten rufen wir uns kurz zusammen, dass ich auch sicher verstehe, was du meinst. Solltest du morgen arbeiten auch gerne dann, sonst Montag Mittag/Nachmittag (01522 7314168 ist meine Nummer)

Folgend noch mein Verständnis zu den Urlaubsansprüchen (mehr zum Strukturieren eigener Gedanken, schwierig so etwas verständlich zu formulieren):

Wenn es um den errechneten Jahresanspruch auf Urlaub geht, sollte der Überstandsbetrag aus dem alten System einfach auf den von Pentacode errechneten restlichen  Jahresanspruch addiert werden --> MA1 Jahresanspruch: 6,75 +13,5 (9 Monate)

Wenn es um den derzeitigen Anspruch (Stichtag 1.7) geht, sollte einfach direkt der Überstandsbetrag mit den derzeitigen Anspruch von Pentacode addiert werden --> MA1 Anspruch 01.07: 6,75 + 0    (3 Monate)
MA1 Anspruch 01.08: 6,75 + (27/12) (4 Monate)

**Comment by J0hhny** [comment]
Siehe Push Request Urlaubsübertrag

**Comment by MaKleSoft** [comment]
@J0hhny "Pull Request" 😉
