### ISSUE TITLE
Autorendarstellung auf Blogseite falsch 

### ISSUE THREAD

**Issue by J0hhny** [pentacode/site#92]
Gerade aufgefallen: die weiteren Blogartikel werden immer mit dem Autor des aktuellen Artikels dargestellt.

Bsp. Artikel von Lorenz offen - jetzt werden auch meine Artikel mit dem Namen von Lorenz angezeigt - anders herum genauso.

![image](https://github.com/pentacode/site/assets/104359585/06d11f07-a98a-4b9c-9af4-8d6af01702e2)

**Comment by pgoodbread** [comment]
Kann ich nicht nachstellen, sieht bei mir gut aus. @MaKleSoft kann geschlossen werden?


https://github.com/pentacode/site/assets/29281252/313b1d17-087a-4a1b-93a6-abb1edd7a6ab

**Comment by MaKleSoft** [comment]
@pgoodbread Ja, hatte ich glaube ich schon behoben und vergessen zu schließen.
